//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DVRMobile.Internationalization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DVRMobile.Internationalization.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thêm Server.
        /// </summary>
        internal static string ADD_NEW_SERVER {
            get {
                return ResourceManager.GetString("ADD_NEW_SERVER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thêm Server Mới.
        /// </summary>
        internal static string ADD_SERVER {
            get {
                return ResourceManager.GetString("ADD_SERVER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thông Báo.
        /// </summary>
        internal static string ALERT {
            get {
                return ResourceManager.GetString("ALERT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tự Động Kết Nối Khi Mở Ứng Dụng.
        /// </summary>
        internal static string AUTO_CONNECT_SERVER {
            get {
                return ResourceManager.GetString("AUTO_CONNECT_SERVER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tên Channel.
        /// </summary>
        internal static string CHANNEL_NAME {
            get {
                return ResourceManager.GetString("CHANNEL_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đóng.
        /// </summary>
        internal static string CLOSE {
            get {
                return ResourceManager.GetString("CLOSE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kết nối server thất bại.
        /// </summary>
        internal static string CONNECT_SERVER_FAILED {
            get {
                return ResourceManager.GetString("CONNECT_SERVER_FAILED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bạn có chắc muốn xóa server.
        /// </summary>
        internal static string DELETE_SERVER_CONFIRM {
            get {
                return ResourceManager.GetString("DELETE_SERVER_CONFIRM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bạn có chắc muốn ngắt kết nối server.
        /// </summary>
        internal static string DISCONNECT_SERVER_CONFIRM {
            get {
                return ResourceManager.GetString("DISCONNECT_SERVER_CONFIRM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chỉnh Sửa Server.
        /// </summary>
        internal static string EDIT_SERVER {
            get {
                return ResourceManager.GetString("EDIT_SERVER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yêu cầu đăng nhập khi mở ứng dụng.
        /// </summary>
        internal static string ENABLE_LOGIN {
            get {
                return ResourceManager.GetString("ENABLE_LOGIN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CÀI ĐẶT CHUNG.
        /// </summary>
        internal static string GENERAL_SETTINGS {
            get {
                return ResourceManager.GetString("GENERAL_SETTINGS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cổng Http.
        /// </summary>
        internal static string HTTP_PORT {
            get {
                return ResourceManager.GetString("HTTP_PORT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thông Tin Phần Mềm.
        /// </summary>
        internal static string INFORMATION {
            get {
                return ResourceManager.GetString("INFORMATION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xem Trực Tiếp.
        /// </summary>
        internal static string LIVE_VIEW {
            get {
                return ResourceManager.GetString("LIVE_VIEW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MẬT KHẨU ĐĂNG NHẬP.
        /// </summary>
        internal static string LOGIN_PASSWORD {
            get {
                return ResourceManager.GetString("LOGIN_PASSWORD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tài khoản hoặc mật khẩu sai.
        /// </summary>
        internal static string LOGIN_SERVER_FAILED {
            get {
                return ResourceManager.GetString("LOGIN_SERVER_FAILED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chưa kết nối server.
        /// </summary>
        internal static string NOT_CONNECT_SERVER {
            get {
                return ResourceManager.GetString("NOT_CONNECT_SERVER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hiển thị {0}/{1} channel lên live.
        /// </summary>
        internal static string NUM_OF_CHANNEL_CHECKED {
            get {
                return ResourceManager.GetString("NUM_OF_CHANNEL_CHECKED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mật khẩu đăng nhập.
        /// </summary>
        internal static string PASSWORD {
            get {
                return ResourceManager.GetString("PASSWORD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mật Khẩu.
        /// </summary>
        internal static string PASSWORD_SERVER {
            get {
                return ResourceManager.GetString("PASSWORD_SERVER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Giữ màn hình luôn luôn sáng.
        /// </summary>
        internal static string PREVENT_SLEEP_MODE {
            get {
                return ResourceManager.GetString("PREVENT_SLEEP_MODE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nhập tên thiết bị cần tìm....
        /// </summary>
        internal static string SEARCH_PLACEHOLDER {
            get {
                return ResourceManager.GetString("SEARCH_PLACEHOLDER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Địa Chỉ IP.
        /// </summary>
        internal static string SERVER_ADDRESS {
            get {
                return ResourceManager.GetString("SERVER_ADDRESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Danh Sách Server.
        /// </summary>
        internal static string SERVER_LIST {
            get {
                return ResourceManager.GetString("SERVER_LIST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tên Server.
        /// </summary>
        internal static string SERVER_NAME {
            get {
                return ResourceManager.GetString("SERVER_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cài Đặt.
        /// </summary>
        internal static string SETTING {
            get {
                return ResourceManager.GetString("SETTING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tài Khoản.
        /// </summary>
        internal static string USERNAME_SERVER {
            get {
                return ResourceManager.GetString("USERNAME_SERVER", resourceCulture);
            }
        }
    }
}
